name: Merge dependabot

on: [pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Dependabot Auto Merge
              uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
